services:
  db:
    image: postgres:16
    container_name: sikassarangan-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - sikassarangan_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sikassarangan-net

  redis:
    image: redis:7-alpine
    container_name: sikassarangan-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - sikassarangan_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sikassarangan-net

  api:
    build: .
    container_name: sikassarangan-api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
    ports:
      - "${API_PORT}:3001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sikassarangan-net


volumes:
  sikassarangan_pgdata:
  sikassarangan_redisdata:

  networks:
  sikassarangan-net:
    name: sikassarangan-net